# Streaming Platforms Datasets Preprocessing

## Titles preprocessing

In [ ]:
import pandas as pd

In [ ]:
titles_amazon = pd.read_csv('/content/titles_amazon.csv')
titles_amazon.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,platform
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family']",['US'],26.0,tt0850645,8.5,1236.0,15.424,7.6,amazon
1,tm3357,Gaslight,MOVIE,A newlywed fears she's going mad when strange ...,1944,NaN,114,"['drama', 'crime', 'romance', 'thriller']",['US'],NaN,tt0036855,7.8,32646.0,15.214,7.5,amazon
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['drama', 'romance', 'war']",['US'],NaN,tt0036868,8.1,68804.0,14.155,7.8,amazon
3,tm19424,Detour,MOVIE,"The life of Al Roberts, a pianist in a New Yor...",1945,NaN,66,"['drama', 'thriller', 'crime']",['US'],NaN,tt0037638,7.3,19015.0,12.480,7.3,amazon
4,tm89464,Miracle on 34th Street,MOVIE,"Kris Kringle, seemingly the embodiment of Sant...",1947,G,96,"['drama', 'comedy', 'family']",['US'],NaN,tt0039628,7.9,51756.0,14.950,7.3,amazon

In [ ]:
titles_disney = pd.read_csv('/content/titles_disney.csv')
titles_disney.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,platform
0,tm89464,Miracle on 34th Street,MOVIE,"Kris Kringle, seemingly the embodiment of Sant...",1947,G,96,"['drama', 'comedy', 'family']",['US'],NaN,tt0039628,7.9,51756.0,14.950,7.300,disney
1,tm6609,The Skeleton Dance,MOVIE,"The clock strikes midnight, the bats fly from ...",1929,NaN,5,"['comedy', 'horror']",['US'],NaN,NaN,NaN,NaN,9.123,7.300,disney
2,tm61729,The Adventures of Ichabod and Mr. Toad,MOVIE,The Wind in the Willows: Concise version of Ke...,1949,G,68,"['fantasy', 'animation', 'horror', 'comedy', '...",['US'],NaN,tt0041094,6.9,17413.0,23.351,6.500,disney
3,tm61052,Cinderella,MOVIE,Cinderella has faith her dreams of a better li...,1950,G,74,"['animation', 'romance', 'family', 'fantasy', ...",['US'],NaN,tt0042332,7.3,170408.0,71.072,7.000,disney
4,tm87946,Dumbo,MOVIE,Dumbo is a baby elephant born with over-sized ...,1941,G,64,"['animation', 'family', 'fantasy', 'drama']",['US'],NaN,tt0033563,7.2,139347.0,70.931,6.996,disney

In [ ]:
titles_hulu = pd.read_csv('/content/titles_hulu.csv')
titles_hulu.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,platform
0,tm89464,Miracle on 34th Street,MOVIE,"Kris Kringle, seemingly the embodiment of Sant...",1947,G,96,"['drama', 'comedy', 'family']",['US'],NaN,tt0039628,7.9,51756.0,14.950,7.300,hulu
1,tm125564,The Rocky Horror Picture Show,MOVIE,"Sweethearts Brad and Janet, stuck with a flat ...",1975,R,100,"['comedy', 'horror']","['GB', 'US']",NaN,tt0073629,7.4,163232.0,24.757,7.472,hulu
2,tm72398,Alien,MOVIE,"During its return to the earth, commercial spa...",1979,R,117,"['horror', 'scifi']","['US', 'GB']",NaN,tt0078748,8.5,926258.0,75.593,8.149,hulu
3,ts20413,M*A*S*H,SHOW,The 4077th Mobile Army Surgical Hospital is st...,1972,TV-PG,26,"['war', 'drama', 'comedy']",['US'],11.0,tt0068098,8.5,61756.0,276.898,7.933,hulu
4,ts8350,20/20,SHOW,ABC's original hour-long news magazine.,1978,NaN,63,['documentation'],['US'],28.0,tt0124932,6.7,2645.0,30.589,6.500,hulu

In [ ]:
titles_netflix = pd.read_csv('/content/titles_netflix.csv')
titles_netflix.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,platform
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,49,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN,netflix
1,tm123933,Jaws,MOVIE,When an insatiable great white shark terrorize...,1975,PG,124,"['horror', 'thriller']",['US'],NaN,tt0073195,8.1,644589.0,44.323,7.700,netflix
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,561006.0,30.613,7.798,netflix
3,tm17792,The Deer Hunter,MOVIE,A group of working-class friends decide to enl...,1978,R,183,"['drama', 'war']","['US', 'GB']",NaN,tt0077416,8.1,354546.0,30.046,7.999,netflix
4,tm69980,The Jerk,MOVIE,After discovering he's not really black like t...,1979,R,94,['comedy'],['US'],NaN,tt0079367,7.1,62759.0,9.166,6.886,netflix

In [ ]:
titles = pd.concat([titles_netflix, titles_amazon, titles_hulu, titles_disney], ignore_index=True)
titles

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,platform
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,49,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN,netflix
1,tm123933,Jaws,MOVIE,When an insatiable great white shark terrorize...,1975,PG,124,"['horror', 'thriller']",['US'],NaN,tt0073195,8.1,644589.0,44.323,7.700,netflix
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,561006.0,30.613,7.798,netflix
3,tm17792,The Deer Hunter,MOVIE,A group of working-class friends decide to enl...,1978,R,183,"['drama', 'war']","['US', 'GB']",NaN,tt0077416,8.1,354546.0,30.046,7.999,netflix
4,tm69980,The Jerk,MOVIE,After discovering he's not really black like t...,1979,R,94,['comedy'],['US'],NaN,tt0079367,7.1,62759.0,9.166,6.886,netflix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22614,tm1347894,More from Pandora's Box: Stunts,MOVIE,"The ""Avatar"" stunt team isn’t just creating br...",2022,NaN,5,[],[],NaN,NaN,NaN,NaN,NaN,NaN,disney
22615,ts392522,Zombies: The Re-Animated Series Shorts,SHOW,An animated short-form series that continues t...,2023,NaN,2,"['comedy', 'animation']",['US'],1.0,tt28074383,7.7,18.0,NaN,NaN,disney
22616,tm1249066,Tangled Sing-Along,MOVIE,NaN,2022,NaN,100,[],['US'],NaN,tt21616602,NaN,NaN,NaN,NaN,disney
22617,ts320286,Meet Spidey and His Amazing Friends - shorts,SHOW,NaN,2021,NaN,5,[],['US'],1.0,NaN,NaN,NaN,NaN,NaN,disney
22618,ts351515,Disney Gallery: Star Wars: The Book of Boba Fett,SHOW,The behind-the-scenes story of the legendary b...,2022,TV-14,60,['documentation'],['US'],1.0,tt19881256,7.5,568.0,NaN,NaN,disney

In [ ]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22619 entries, 0 to 22618
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    22619 non-null  object
 1   title                 22619 non-null  object
 2   type                  22619 non-null  object
 3   description           22492 non-null  object
 4   release_year          22619 non-null  int64
 5   age_certification     11497 non-null  object
 6   runtime               22619 non-null  int64
 7   genres                22619 non-null  object
 8   production_countries  22619 non-null  object
 9   seasons               6214 non-null   float64
 10  imdb_id               20918 non-null  object
 11  imdb_score            20473 non-null  float64
 12  imdb_votes            20420 non-null  float64
 13  tmdb_popularity       22075 non-null  float64
 14  tmdb_score            20336 non-null  float64
 15  platform              22619 non-null  object
dtypes: float64(5), int64(2), object(9)
memory usage: 2.8+ MB

In [ ]:
titles[titles['age_certification'].isna()].head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,platform
13,tm16479,White Christmas,MOVIE,Two talented song-and-dance men team up after ...,1954,NaN,120,"['comedy', 'romance']",['US'],NaN,tt0047673,7.5,47128.0,13.656,7.202,netflix
14,tm16812,Bandie,MOVIE,Maharaj Brajbhan lives a wealthy lifestyle in ...,1978,NaN,141,"['drama', 'action', 'romance']",['IN'],NaN,tt1219315,4.7,39.0,0.840,6.000,netflix
15,tm75975,Prince,MOVIE,"To better himself, a spoiled prince temporaril...",1969,NaN,152,"['drama', 'romance']",['IN'],NaN,tt0064842,6.9,214.0,2.888,5.000,netflix
19,tm71909,Amrapali,MOVIE,"After a failed conquest, Emperor Ajaatshatru p...",1966,NaN,120,['fantasy'],['IN'],NaN,tt0060104,6.7,266.0,0.884,6.000,netflix
20,tm107372,Manoranjan,MOVIE,Havaldar Ratan is a rookie at the local police...,1974,NaN,162,"['comedy', 'drama', 'romance']",['IN'],NaN,tt0071811,6.5,276.0,0.968,4.500,netflix

In [ ]:
print(f"There are {len(titles[titles['age_certification'].isna()])} movies and tv shows which are not rated for age restrictions.")

There are 11122 movies and tv shows which are not rated for age restrictions.

Let's replace these `null` values with `Not rated`:

In [ ]:
titles['age_certification'].fillna('Not rated', inplace=True)

Even though columns `genres` and `production_countries` don't have `null` values, there are some rows with unspecified genres and production countries accordingly, which looks like `[]`. Let's replace these values to `unspecified`:

In [ ]:
titles['genres'].replace('[]', 'unspecified', inplace=True)

In [ ]:
titles['production_countries'].replace('[]', 'unspecified', inplace=True)

In [ ]:
print(f"In the column 'seasons' there are {len(titles[titles['seasons'].isna()])} null values.")

In the column 'seasons' there are 16405 null values.

Let's see how many of these `null` values are related to tv shows:

In [ ]:
titles[titles['seasons'].isna()]['type'].value_counts()

MOVIE    16405
Name: type, dtype: int64

We can see that all of these `null` values are only related to movies. In this case we can replace them with `0`, since movies don't have seasons:

In [ ]:
titles['seasons'].fillna(0, inplace=True)

In [ ]:
print(f"There are also {len(titles[titles['imdb_score'].isna()])} null values in the 'imdb_score' column and {len(titles[titles['imdb_votes'].isna()])} null values in the 'imdb_votes' column.")

There are also 2146 null values in the 'imdb_score' column and 2199 null values in the 'imdb_votes' column.

Let's replace them with `0`:

In [ ]:
titles['imdb_score'].fillna(0, inplace=True)
titles['imdb_votes'].fillna(0, inplace=True)

We are not planning to use `imdb_id` column, but anyway let's replace `null` values in this column with `Not rated`:

In [ ]:
titles['imdb_id'].fillna('Not rated', inplace=True)

In [ ]:
print(f"There are {titles.duplicated().sum()} duplicated records in the dataset.")

There are 0 duplicated records in the dataset.

In [ ]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22619 entries, 0 to 22618
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    22619 non-null  object
 1   title                 22619 non-null  object
 2   type                  22619 non-null  object
 3   description           22492 non-null  object
 4   release_year          22619 non-null  int64
 5   age_certification     22619 non-null  object
 6   runtime               22619 non-null  int64
 7   genres                22619 non-null  object
 8   production_countries  22619 non-null  object
 9   seasons               22619 non-null  float64
 10  imdb_id               22619 non-null  object
 11  imdb_score            22619 non-null  float64
 12  imdb_votes            22619 non-null  float64
 13  tmdb_popularity       22075 non-null  float64
 14  tmdb_score            20336 non-null  float64
 15  platform              22619 non-null  object
dtypes: float64(5), int64(2), object(9)
memory usage: 2.8+ MB

In [ ]:
print(f"In the column 'description' there are {len(titles[titles['description'].isna()])} null values.")

In the column 'description' there are 127 null values.

But we will leave these `null` values in the `description` column as it is, it is not critical in this case.

Let's remove columns we are not planning to use: `tmdb_popularity` and `tmdb_score`:

In [ ]:
titles = titles.drop(['tmdb_popularity','tmdb_score'], axis=1)
titles.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,platform
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,49,['documentation'],['US'],1.0,Not rated,0.0,0.0,netflix
1,tm123933,Jaws,MOVIE,When an insatiable great white shark terrorize...,1975,PG,124,"['horror', 'thriller']",['US'],0.0,tt0073195,8.1,644589.0,netflix
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],0.0,tt0071853,8.2,561006.0,netflix
3,tm17792,The Deer Hunter,MOVIE,A group of working-class friends decide to enl...,1978,R,183,"['drama', 'war']","['US', 'GB']",0.0,tt0077416,8.1,354546.0,netflix
4,tm69980,The Jerk,MOVIE,After discovering he's not really black like t...,1979,R,94,['comedy'],['US'],0.0,tt0079367,7.1,62759.0,netflix

In [ ]:
titles.to_csv('titles_all.csv', index=False)

## Credits preprocessing

In [ ]:
credits_amazon = pd.read_csv('/content/credits_amazon.csv')
credits_amazon.head()

   person_id       id          name  character   role platform
0      31460  ts20945    Moe Howard        Moe  ACTOR   amazon
1      31461  ts20945    Larry Fine      Larry  ACTOR   amazon
2     133879  ts20945  Curly Howard      Curly  ACTOR   amazon
3      69525  ts20945  Shemp Howard      Shemp  ACTOR   amazon
4      93220  ts20945    Joe DeRita  Curly Joe  ACTOR   amazon

In [ ]:
credits_disney = pd.read_csv('/content/credits_disney.csv')
credits_disney.head()

   person_id       id            name         character   role platform
0      35549  tm89464  Maureen O'Hara      Doris Walker  ACTOR   disney
1      57832  tm89464      John Payne       Fred Gailey  ACTOR   disney
2      57833  tm89464    Edmund Gwenn      Kris Kringle  ACTOR   disney
3      25096  tm89464    Natalie Wood      Susan Walker  ACTOR   disney
4      27185  tm89464     Porter Hall  Granville Sawyer  ACTOR   disney

In [ ]:
credits_hulu = pd.read_csv('/content/credits_hulu.csv')
credits_hulu.head()

   person_id       id            name         character   role platform
0      35549  tm89464  Maureen O'Hara      Doris Walker  ACTOR     hulu
1      57832  tm89464      John Payne       Fred Gailey  ACTOR     hulu
2      57833  tm89464    Edmund Gwenn      Kris Kringle  ACTOR     hulu
3      25096  tm89464    Natalie Wood      Susan Walker  ACTOR     hulu
4      27185  tm89464     Porter Hall  Granville Sawyer  ACTOR     hulu

In [ ]:
credits_netflix = pd.read_csv('/content/credits_netflix.csv')
credits_netflix.head()

,person_id,id,name,character,role,platform
0,11249,tm123933,Roy Scheider,Police Chief Martin Brody,ACTOR,netflix
1,26228,tm123933,Robert Shaw,Quint,ACTOR,netflix
2,4021,tm123933,Richard Dreyfuss,Matt Hooper,ACTOR,netflix
3,14386,tm123933,Murray Hamilton,Mayor Larry Vaughn,ACTOR,netflix
4,19479,tm123933,Lorraine Gary,Ellen Brody,ACTOR,netflix

In [ ]:
credits = pd.concat([credits_netflix, credits_amazon, credits_hulu, credits_disney], ignore_index=True)
credits

,person_id,id,name,character,role,platform
0,11249,tm123933,Roy Scheider,Police Chief Martin Brody,ACTOR,netflix
1,26228,tm123933,Robert Shaw,Quint,ACTOR,netflix
2,4021,tm123933,Richard Dreyfuss,Matt Hooper,ACTOR,netflix
3,14386,tm123933,Murray Hamilton,Mayor Larry Vaughn,ACTOR,netflix
4,19479,tm123933,Lorraine Gary,Ellen Brody,ACTOR,netflix
...,...,...,...,...,...,...
326172,2368318,tm1239803,Guthierry Sotero,Self,ACTOR,disney
326173,211312,tm1239803,Daniel Botelho,Self,ACTOR,disney
326174,299279,tm1239803,Suzy Milstein,NaN,DIRECTOR,disney
326175,1268241,tm1239803,Luiza Trigo,NaN,DIRECTOR,disney
326176,2466915,tm1239803,Juliana Vonlanten,NaN,DIRECTOR,disney

In [ ]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326177 entries, 0 to 326176
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   person_id  326177 non-null  int64
 1   id         326177 non-null  object
 2   name       326177 non-null  object
 3   character  292565 non-null  object
 4   role       326177 non-null  object
 5   platform   326177 non-null  object
dtypes: int64(1), object(5)
memory usage: 14.9+ MB

In [ ]:
print(f"In the column 'character' there are {len(credits[credits['character'].isna()])} null values.")

In the column 'character' there are 33612 null values.

In [ ]:
len(credits[(credits['character'].isna()) & (credits['role'] != 'DIRECTOR')])

15047

And about half of these `null` values belong to `DIRECTOR` role, who doesn't have a character. Since we are not planning to use this column, we just leave it as it is.

In [ ]:
credits.to_csv('credits_all.csv', index=False)